### ISSUE TITLE
Does Monitor work? 

### ISSUE THREAD

**Issue by fbalaban** [SDFIdk/CDSETool#108]
## Summary
I have used the `download_features` function as described but Monitor does not seem to indicate progress

**Comment by pedep** [comment]
@fbalaban Could you provide a minimal example to demostrate when or how the monitor does not work? Does the example from `Quick Start` in the readme also not work?

In addition to this, knowing which cdsetool version, python version, terminal emulator, shell and operating system would be a major help with debugging :nerd_face:

**Comment by pjonsson** [comment]
I don't have a typical setup, but for what it is worth, I have never seen any progress indication in any version from ~December until now when calling `download_feature` with the StatusMonitor as a part of options. Before #59, I was digging around in the internals of the StatusMonitor to figure out if a download was successful, so the monitor is definitely "attached".

I'm on Ubuntu 22.04 LTS and using the "Terminal" in whatever the default desktop environment is. My Python environment is the python:3.10-slim docker image, but with an added regular user, and `TERM=xterm` inside the container. I'm using bash as shell in both the terminal and the container.

I recently debugged some other download, and that threw up a progress bar in my terminal (using tqdm as this issue initially mentioned) in the same environment, so I don't think my environment is inherently incapable of displaying a progress bar. Beyond tqdm, my Python environment also has the typer package with `"all"` extras, and the logfmter package, so I'm guessing plenty of other things could interfere.

My environment cannot be taken apart easily, so I think it's better to work with @fbalaban for resolving this issue. If I suddenly get progress bars in the future I will comment here.

**Comment by pedep** [comment]
I have performed tests in these environments using cdsetool==0.2.8

- bookworm, urxvt, zsh
- bookworm, urxvt, bash
- bookworm, xterm, zsh
- bookworm, xterm, bash
- bookwork, xfce-terminal, bash
- python:3.10-slim, urxvt, bash
- python:3.10-slim, xterm, bash
- python:3.10-slim, xfce-terminal, bash

with this test script (the example from readme minus the shapefile filter)

```python
from cdsetool.query import query_features, shape_to_wkt
from cdsetool.credentials import Credentials
from cdsetool.download import download_features
from cdsetool.monitor import StatusMonitor
from datetime import date

features = query_features(
    "Sentinel1",
    {
        "startDate": "2020-12-20",
        "completionDate": date(2020, 12, 25),
        "processingLevel": "LEVEL1",
        "sensorMode": "IW",
        "productType": "IW_GRDH_1S"
    },
)

list(
    download_features(
        features,
        "out",
        {
            "concurrency": 2,
            "monitor": StatusMonitor(),
            "credentials": Credentials("myuseername@email.com", "mypassword")
        },
    )
)
```

and i have no problem getting the expected progressbars

```
[[  | 2 files in progress | 0 files done | 146.80 MB total downloaded | 7.86 MB/s ]]
S1B_IW_GRDH_1SDV_20201219T230016_20201219T230041_024777_02F299_8E78.zip 1.77 GB (6%)   
[█████                                                                                ]
S1A_IW_GRDH_1SDV_20201219T230017_20201219T230042_035761_042F74_B48D.zip 1.71 GB (1%)   
[█                                                                                    ]
```

Just to make sure nothing is wrong with `download_feature`, i also tested like this with no issues.

```python
from cdsetool.query import query_features, shape_to_wkt
from cdsetool.credentials import Credentials
from cdsetool.download import download_feature
from cdsetool.monitor import StatusMonitor
from datetime import date

features = query_features(
    "Sentinel1",
    {
        "startDate": "2020-12-20",
        "completionDate": date(2020, 12, 25),
        "processingLevel": "LEVEL1",
        "sensorMode": "IW",
        "productType": "IW_GRDH_1S"
    },
)

with StatusMonitor() as monitor:
    for feature in features:
        download_feature(
            feature,
            "out",
            {
                "monitor": monitor,
                "credentials": Credentials("myuseername@email.com", "mypassword")
            }
        )
```

**Comment by fbalaban** [comment]
Hey @pedep ,
initially I apologize because I had brought up the issue with tqdm and then edited it, questioning Monitor.
To be honest, since Monitor was in the [Roadmap list](https://github.com/SDFIdk/CDSETool?tab=readme-ov-file#roadmap), (and I had not used the Quick start example), I have not properly investigated if it is indeed working or not.  Let me get back to you in a couple of days checking my containers.

**Comment by fbalaban** [comment]
Hi again @pedep,

I find no issues now with Monitor, even thought it does not refresh properly inside a container, but this does not seem to be a problem with cdsetool.

I will close this issue now. Thanks and sorry for the confusion
