### ISSUE TITLE
Credentials: Invalid token type

### ISSUE THREAD

**Issue by Lotuss91** [SDFIdk/CDSETool#117]
Hi all,
this is likely not a bug but I can't understand what is happening.
When trying to validate/logging in with my Copernicus credentials using the code below:
```python
from cdsetool import credentials

credentials.validate_credentials(username="username", password="password")
```
I get this error:
```python
DecodeError: Invalid token type. Token must be a <class 'bytes'>
```

I tested the same code in Google Colab and everything worked correctly. My guess is that since I'm working from the pc of my company, there may be a firewall of some sort that messes things up.

However, if I try a normal query such this:
```python
features = query_features(
    "Sentinel1",
    {
        "startDate": "2020-12-20",
        "completionDate": date(2020, 12, 25),
        "processingLevel": "LEVEL1",
        "sensorMode": "IW",
        "productType": "IW_GRDH_1S",
        "geometry": geometry,
    },
)
```
everything works. So maybe the issue is with the encryption of the credential?

Thanks

**Comment by pjonsson** [comment]
I don't know about the DecodeError, but the reason you can still do queries is probably because those do not require you to be authenticated.

**Comment by Lotuss91** [comment]
I may have found the problem or at least a temporary solution.

The firewall hypothesis was wrong so  I started debugging the credentials.py and realized that when executing the code line by line, the authentication was sucessful.
 The issue I found is that in the constructor, ```self.__ensure_tokens()```  is called just right after the definition of the token expiration times.
```python
        self.__access_token = None
        self.__refresh_token = None
        self.__access_token_expires = datetime.now()
        self.__refresh_token_expires = datetime.now()

        self.__lock = threading.Lock()

        if self.__username is None or self.__password is None:
            self.__read_credentials()

        self.__ensure_tokens()
```  

When in ```__ensure_tokens``` the expiration dates are checked:
```python
    def __ensure_tokens(self):
        with self.__lock:
            if self.__access_token_expires < datetime.now():
                if self.__refresh_token_expires < datetime.now():
``` 
it seems like (not 100% sure though) that no time has passed and so the if conditions fail leading to a call to ```self.__jwk_client.get_signing_key_from_jwt(self.__access_token)``` with a None token (since ```self.__token_exchange(data)``` is not called).

The solution I'm using (even though quite janky) is to add a ```time.sleep(0.1)``` in the constructor just after the  ```self.__lock = threading.Lock()```.

I hope this helps in finding a more reliable solution.

**Comment by pjonsson** [comment]
What platform and Python version are you on?

Are you using PyPy or some other heavily optimizing Python implementation?

**Comment by Lotuss91** [comment]
Windows and Python 3.12.2.

I'm not using PyPy or anything fancy. Just a Python installation using miniconda and an environment where I installed only cdsetool with pip.

**Comment by pjonsson** [comment]
I don't know anything about timer resolution on Windows, or optimizations in recent Python versions, but can you try the fix in #123 and see if that works for you?

**Comment by Lotuss91** [comment]
Yep, that works. 
Similar in concept to the time sleep but more elegant.
The timedealta can be of just 0.1 seconds.

**Comment by pjonsson** [comment]
> The timedealta can be of just 0.1 seconds.

I thought a bit about this and a 1 minute/week clock drift on a laptop isn't unheard of, and depending on configuration, ntp can move time backwards.

Since we have to have the time delta in the initialization, it's better to just set it to something clearly different so it's easy to tell what kind of time it is when debugging. I used 8 hours to be far beyond reasonable clock drift and impossible to mistake AM for PM or vice versa.

**Comment by Lotuss91** [comment]
Make sense, thanks.

I think that the bug should be considered corrected.
