### ISSUE TITLE
GDAL warning when running script

### ISSUE THREAD

**Issue by subnet001** [SDFIdk/CDSETool#14]
```
Warning 3: Cannot find header.dxf (GDAL_DATA is not defined)
Cannot find header.dxf (GDAL_DATA is not defined)
```

probably stems from shape file conversion?

**Comment by pedep** [comment]
could you provide a minimal example that reproduces this warning?

**Comment by subnet001** [comment]
shape_to_wkt('stavis_odense/POLYGON.shp')

[stavis_odense.zip](https://github.com/SDFIdk/CDSETool/files/13390527/stavis_odense.zip)

**Comment by pedep** [comment]
I am not able to reproduce this warning. Are you certain this is not caused to something specific to your python installation?
Could you try creating a fresh python venv and only install `cdsetool`? `cdsetool` does not depend on GDAL, so having a GDAL error originating from `cdsetool` would be highly unusual.

**Comment by EmanuelCastanho** [comment]
I am not able to reproduce this warning. However, I can suggest the following:
1- As @pedep said, create a freshly new environment only with `cdsetool`;
2- If you need to use Geopandas and GDAL together in the same environment try this (works for me):
```
conda create -n CDSETool-env python=3.9
conda activate CDSETool-env
conda install -c conda-forge gdal=3.5.0 
pip install geopandas
pip install cdsetool
```
Sometimes Geopandas and GDAL are not good friends in the same environment and you need to try different installation options...
3- Share your environment.

**Comment by subnet001** [comment]
That resolved it. It appears that GDAL was the reason here.
