### ISSUE TITLE
[Question] Which credentials are needed to obtain data

### ISSUE THREAD

**Issue by langelrhea** [SDFIdk/CDSETool#32]
Hello all!

First of all, thank you so much for your work. 
I would like to ask which credentials are needed to obtain data from Sentinel. I have attempted to run the [Quick Start](https://github.com/SDFIdk/CDSETool#quick-start), but I cannot retrieve any data. I have tried using both my CDSE email and password, as well as my OAuth client ID and password, but I receive the following response:

    session = options.get("credentials", Credentials()).get_session()

S1B_IW_GRDH_1SDV_20201224T164755_20201224T164820_024847_02F4D0_5984.SAFE skipped
S1B_IW_GRDH_1SDV_20201224T164730_20201224T164755_024847_02F4D0_5CE0.SAFE skipped
S1A_IW_GRDH_1SDV_20201224T045715_20201224T045740_035823_043187_6D29.SAFE skipped
S1B_IW_GRDH_1SDV_20201224T164730_20201224T164755_024847_02F4D0_08CA.SAFE skipped
S1B_IW_GRDH_1SDV_20201224T164755_20201224T164820_024847_02F4D0_F1D9.SAFE skipped
S1A_IW_GRDH_1SDV_20201224T045650_20201224T045715_035823_043187_AA47.SAFE skipped
S1A_IW_GRDH_1SDV_20201224T045650_20201224T045715_035823_043187_0A19.SAFE skipped
S1A_IW_GRDH_1SDV_20201224T045625_20201224T045650_035823_043187_4B74.SAFE skipped
[[  | 0 files in progress | 8 files done | 0 B total downloaded | 0.0 B/s ]]

Do you know what is happening?

**Comment by subnet001** [comment]
Hi, thanks for the report! I can't reproduce your bug with the quick start after putting in a shape and my own credentials but we've just released 0.2.0 so that might have fixed it. 

There has also recently been a breakdown of the CDSE services, which might have coincided with your attempts.
https://forum.step.esa.int/t/access-to-orbit-files-from-1-november-2023/40777/14?

In general, if the credentials can log into CDSEs site (https://dataspace.copernicus.eu/) they'll work here. Also did you use .netrc or put the credentials into the script itself?

**Comment by langelrhea** [comment]
Hello @subnet001 
I upgrade the library to 0.2.0 version, but I have another issue. Check my code and the type error.

from cdsetool.query import query_features, shape_to_wkt
from cdsetool.credentials import Credentials
from cdsetool.download import download_features
from cdsetool.monitor import StatusMonitor
from datetime import date

features = query_features(
    "Sentinel1",
    {
        "startDate": "2020-12-20",
        "completionDate": date(2020, 12, 25),
        "processingLevel": "LEVEL1",
        "sensorMode": "IW",
        "productType": "IW_GRDH_1S",
        "geometry": shape_to_wkt("/home/user/folder/example.geojson"),
    },
)

list(
    download_features(
        features,
        "/home/user/folder/",
        {
            "concurrency": 4,
            "monitor": StatusMonitor,
            "credentials": Credentials("my_email@domain.com", "password"),
        },
    )
)

**Comment by langelrhea** [comment]
Hello @subnet001 
Thank you for your comment! It seems that it was a breakdown of the CDSE services.
 Now I'm able to download Sentinel images!

Thank you so much for your support and work.
Best regards!
