### ISSUE TITLE
replace os.get_terminal_size() by shutil.get_terminal_size()

### ISSUE THREAD

**Issue by masopust** [SDFIdk/CDSETool#45]
## Describe the bug
Cannot download features outside Python terminal, in my case in the Jupyter notebook. 
It is caused by the usage of os.get_terminal_size() in monitor.py file
Please replace this function by shutil.get_terminal_size() and you can run it without terminal also.

### Steps to reproduce
```python
from cdsetool.monitor import StatusMonitor
```
---------------------------------------------------------------------------
OSError                                   Traceback (most recent call last)
/tmp/ipykernel_27/2722933232.py in <cell line: 1>()
----> 1 from cdsetool.monitor import StatusMonitor

/opt/conda/lib/python3.9/site-packages/cdsetool/monitor.py in <module>
     22 
     23 
---> 24 _set_line_length(None, None)
     25 
     26 # handle sigwinch on linux

/opt/conda/lib/python3.9/site-packages/cdsetool/monitor.py in _set_line_length(_signal_num, _stack)
     19 def _set_line_length(_signal_num, _stack):
     20     global LINE_LENGTH  # pylint: disable=global-statement
---> 21     LINE_LENGTH, _ = os.get_terminal_size()
     22 
     23 

OSError: [Errno 25] Inappropriate ioctl for device

### Expected behavior
You can run this package in any enviroment like Jupyter, IDE, ...

### Environment
 - OS: Jupyter Notebook
 - Package version: cdsetool==0.2.0
 - Python version: 3.9.18
 - Selected Jupyter core packages...
IPython          : 7.34.0
ipykernel        : 6.19.2
ipywidgets       : 7.7.2
jupyter_client   : 6.1.12
jupyter_core     : 4.11.2
jupyter_server   : 1.21.0
jupyterlab       : not installed
nbclient         : 0.7.0
nbconvert        : 7.2.1
nbformat         : 5.6.1
notebook         : 6.5.4
qtconsole        : not installed
traitlets        : 5.5.0

**Comment by pedep** [comment]
Thank you for bringing up this issue.
The project in general does not have very good jupyter and ipython support. This will be fixed!

I have started a branch here #46, where i will fix a few issues i encountered using CDSETool in a jupyter notebook. I hope to finish soon, and will keep you posted in this thread :+1:

**Comment by pedep** [comment]
v0.2.1 has been published :rocket: You should be able to install it now with `pip install cdsetool=0.2.1`
