### ISSUE TITLE
Geopandas is a heavy dependency, could a lighter weight package be used instead?

### ISSUE THREAD

**Issue by craigmillernz** [SDFIdk/CDSETool#52]
## Summary
Geopandas is a very heavy dependency for simply reading a shapefile and often creates conflicts with other packages.
Could a lighter weight module such as shapely or pyshp be used instead?
https://shapely.readthedocs.io/en/stable/index.html
https://pypi.org/project/pyshp/

**Comment by pedep** [comment]
While i agree gpd is probably too big for what we are using it for, we might need to keep if it we implement https://github.com/SDFIdk/CDSETool/issues/38

We could probably go for a conditional implementation with geopandas and shapely as optional dependencies, using either shapely or geopandas depending on whats installed, and erroring when none of them are installed.

**Comment by craigmillernz** [comment]
Sounds good.  If your requirement is just to select a geopgraphical subset then shapely might be all that is needed, and that can be up to user to decide?  Perhaps shapely as minimum and gpd as optional?

**Comment by pedep** [comment]
Yes, i was going for something along those lines :+1:

**Comment by pedep** [comment]
@subnet001 Just go for removing geopandas as a dependency and swap it for pyshp or shapely.
I think pyshp is lighter and has no dependencies but less actively maintained, while shapely is more active but requires numpy

**Comment by subnet001** [comment]
After a bunch of experimentation I think i must conclude that I can't get pyshp/shapely to work consistently for all shapefiles. If anyone is up to the challenge of implementing them in stead, I'd welcome it.

I'm going to change Geopandas to a required dependency to avoid any confusion.  For now I'm closing the issue.
