### ISSUE TITLE
Return error indication from download_feature 

### ISSUE THREAD

**Issue by pjonsson** [SDFIdk/CDSETool#59]
## Summary

It would be nice to be able to distinguish success from failure when calling `download_feature`.

### Basic example

```python
if download_feature(..) is None:
   print("Failed to download")
```

### Motivation

The expected outcome is that success can be determined by the caller without performing file system operations and without digging around in data structures internal of CDSETool.

**Comment by pedep** [comment]
Great suggestion :+1:

We will get around to this soon, unless someone wants to submit a PR? :)
