### ISSUE TITLE
Failing download_feature because of 401 response

### ISSUE THREAD

**Issue by pjonsson** [SDFIdk/CDSETool#60]
## Describe the bug

I get intermittent 401 (login failed) responses which causes CDSETool to throw an exception and resulting in failed downloads.

### Steps to reproduce

Download things and wait for the 401 to appear. When the 401 happens, wait a few minutes and try again, and the download will complete.

### Expected behavior

The issue is with the remote site rather than CDSETool, but since CDSETool is the interface to the remote, it would be nice with some kind of workaround in CDSETool to alleviate the issue.

It would be nice with a `retries` option somewhere (with a default value of 0), so the client could sleep for a while and then try again before resorting to throwing exceptions. If there is a retries option, there should probably also be some way to configure how long to wait before trying again. Not sure what a good default value for that would be, maybe 120 seconds?

### Environment
 - OS: Ubuntu 22.04
 - Package version: 0.2.3 from PyPi
 - Python version: 3.10

**Comment by pedep** [comment]
I have tried to reproduce this issue, but am unable to get a 401 response.

Do you happen to have captured a stacktrace of when this happened?


We currently have a retry mechanism implemented to handle 429 responses when downloading files https://github.com/SDFIdk/CDSETool/blob/main/src/cdsetool/download.py#L96-L102

Does this not handle the 401 responses you receive?

**Comment by pjonsson** [comment]
Unfortunately I don't have a backtrace available, but `get_session()` (which throws `InvalidCredentialsException`) is called: https://github.com/SDFIdk/CDSETool/blob/b600f8dc51b3710dd4c0de926b2584f49143c67e/src/cdsetool/download.py#L36 before  `_retry_backoff()`?

**Comment by pjonsson** [comment]
Let me be clear: I don't think there is an issue in CDSETool itself, I think the issue is the other end. But it would be nice if CDSETool made an attempt to paper over that issue, so users wouldn't notice a hiccup in the other end, just when the other end really is down for real.

**Comment by pedep** [comment]
@pjonsson Thank you for providing this insightful backtrace 

This makes it very clear that copernicus has some intermittency issues with their authentication servers, and we should definitely handle this with retry-backoff in the Credentials class.

I will draft a pull request and link it to this issue.

**Comment by pedep** [comment]
closing this in favor of #84
